---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: druid-exporter
spec:
  selector:
    matchLabels:
      druid: metrics
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        druid: metrics
    spec:
      containers:
      - env:
        - name: DRUID_URL
          value: http://10.100.48.45:8088
        image: quay.io/opstree/druid-exporter:v0.5
        imagePullPolicy: IfNotPresent
        name: druid-exporter
        ports:
        - containerPort: 8080
          protocol: TCP
