name: Installs the Demo
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - name: azure-login
      uses: azure/login@v1
      env: 
          credentials: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: installs the demo
      if: success()
      run: bash run.sh -x install
